namespace TS.FW.XCom.SDC.OLED.V227
{
    public enum eRCMD
    {
        JOB_PROCESS_START = 1,
        JOB_PROCESS_CANCEL,
        JOB_PROCESS_ABORT,

        GLASS_PROCESS_START = 11,
        GLASS_PROCESS_CANCEL,
        GLASS_PROCESS_ABORT,
        GLASS_PROCESS_END,

        JOB_PROCESS_START_PERMISSION = 30,

        RELOAD_CASSETTE = 36,

        EQUIPMENT_PROCESS_STATE_PAUSE = 51,
        EQUIPMENT_PROCESS_STATE_RESUME,
        EQUIPMENT_STATE_CHANGE_TO_PM,
        EQUIPMENT_STATE_CHANGE_TO_NORMAL,
        EQUIPMENT_PROCESS_STATE_DISABLED,
        EQUIPMENT_PROCESS_STATE_ENABLED,

        MASK_STOCK_CHAMBER_VENT_COMMAND_EVP = 81,

        MASK_STOCK_CHAMBER_VACUUM_COMMAND_EVP = 83,

        MASK_STOCK_CHAMBER_REUSE_MODE_ON_EVP = 85,
        MASK_STOCK_CHAMBER_REUSE_MODE_OFF_EVP,

        MASK_STOCK_CHAMBER_LOAD_REQUEST_COMMAND_EVP = 91,

        MASK_STOCK_UPPER_CHAMBER_UNLOAD_REQUEST_COMMAND_EVP = 94,
        MASK_STOCK_LOWER_CHAMBER_UNLOAD_REQUEST_COMMAND_EVP,
        MASK_STOCK_ALL_CHAMBER_UNLOAD_REQUEST_COMMAND_EVP,

        IN_EQ_PATH_CHANGE_COMMAND_EVP = 132,

        SORTING_JOB_PROCESS_START = 301,
        SORTING_JOB_PROCESS_CANCEL,
        SORTING_JOB_PROCESS_ABORT,
        SORTING_JOB_PROCESS_END,
        SCAN_JOB_PROCESS_START,
        SCAN_JOB_PROCESS_END,

        MATERIAL_JOB_PROCESS_START = 1001,
        MATERIAL_JOB_PROCESS_CANCEL,
        MATERIAL_JOB_PROCESS_ABORT,

        MATERIAL_PROCESS_START = 1011,
        MATERIAL_PROCESS_CANCEL,
        MATERIAL_PROCESS_ABORT,
        MATERIAL_PROCESS_END,

        MATERIAL_JOB_PROCESS_START_PERMISSION = 1030,
    }
}
